"""Replay motion from csv file(s) and output them to npz file(s)."""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

import numpy as np

from isaaclab.app import AppLauncher


parser = argparse.ArgumentParser(description="Replay motion from csv file(s) and output them to npz file(s).")
input_group = parser.add_mutually_exclusive_group(required=True)
input_group.add_argument("--input_file", type=str, help="Path to one input motion csv file.")
input_group.add_argument("--input_dir", type=str, help="Directory containing multiple motion csv files.")
input_group.add_argument("--input_manifest", type=str, help="JSON manifest generated by pkl_to_csv.py.")
parser.add_argument("--input_fps", type=float, default=30.0, help="The fps of the input motion.")
parser.add_argument(
    "--frame_range",
    nargs=2,
    type=int,
    metavar=("START", "END"),
    help=(
        "frame range: START END (both inclusive). The frame index starts from 1. "
        "Only supported in single-file mode."
    ),
)
parser.add_argument("--output_name", type=str, help="Output motion npz path for single-file mode.")
parser.add_argument("--output_dir", type=str, help="Output directory for batch mode.")
parser.add_argument("--output_fps", type=float, default=50.0, help="The fps of the output motion.")
parser.add_argument("--pattern", type=str, default="*.csv", help="Glob pattern for batch mode.")
parser.add_argument("--recursive", action="store_true", help="Recursively search input_dir in batch mode.")
parser.add_argument("--manifest_path", type=str, default=None, help="Optional JSON manifest path for batch mode.")
parser.add_argument("--overwrite", action="store_true", help="Overwrite existing output files in batch mode.")
parser.add_argument("--robot", choices=["k1", "t1"], default=None, help="Target Booster robot.")

AppLauncher.add_app_launcher_args(parser)
args_cli = parser.parse_args()

if args_cli.input_file and not args_cli.output_name:
    parser.error("--output_name is required when using --input_file")
if (args_cli.input_dir or args_cli.input_manifest) and not args_cli.output_dir:
    parser.error("--output_dir is required when using --input_dir or --input_manifest")
if args_cli.frame_range is not None and not args_cli.input_file:
    parser.error("--frame_range is only supported in single-file mode")
if args_cli.input_dir and args_cli.robot is None:
    parser.error("--robot is required when using --input_dir")

app_launcher = AppLauncher(args_cli)
simulation_app = app_launcher.app

import torch

import isaaclab.sim as sim_utils
from isaaclab.scene import InteractiveScene
from isaaclab.sim import SimulationContext

from booster_train.assets.robots.booster import BOOSTER_K1_CFG, BOOSTER_T1_CFG
from booster_assets.motions import K1_JOINT_NAMES, T1_JOINT_NAMES
from _motion_io_common import load_motion_csv
from _motion_to_npz_common import MotionSequence, make_replay_scene_cfg, save_motion_npz


ROBOT_MAP = {
    "k1": (BOOSTER_K1_CFG, K1_JOINT_NAMES),
    "t1": (BOOSTER_T1_CFG, T1_JOINT_NAMES),
}

ROBOT_ALIAS = {
    "k1": "k1",
    "t1": "t1",
    "booster_k1": "k1",
    "booster_t1": "t1",
}


def _normalize_robot_name(robot_name: str | None) -> str | None:
    if robot_name is None:
        return None
    normalized = ROBOT_ALIAS.get(str(robot_name))
    if normalized is None:
        raise ValueError(f"Unsupported robot name: {robot_name}. Supported: {sorted(ROBOT_ALIAS)}")
    return normalized


def _resolve_manifest_entries(manifest_path: str | Path) -> list[dict]:
    manifest_path = Path(manifest_path)
    manifest_data = json.loads(manifest_path.read_text(encoding="utf-8"))
    if isinstance(manifest_data, dict):
        entries = manifest_data.get("motions", manifest_data.get("files", []))
    elif isinstance(manifest_data, list):
        entries = manifest_data
    else:
        raise TypeError(f"Unsupported manifest format in {manifest_path}")

    manifest_dir = manifest_path.parent
    resolved = []
    for entry in entries:
        if isinstance(entry, str):
            csv_path = entry
            robot_name = None
            input_fps = args_cli.input_fps
            relative_path = None
        elif isinstance(entry, dict):
            csv_path = entry.get("csv_file") or entry.get("output_file") or entry.get("file")
            if csv_path is None:
                raise KeyError(f"Manifest entry missing csv_file/output_file/file: {entry}")
            robot_name = _normalize_robot_name(entry.get("robot_type"))
            input_fps = float(entry.get("input_fps", args_cli.input_fps))
            relative_path = entry.get("relative_path")
        else:
            raise TypeError(f"Unsupported manifest entry: {entry}")

        csv_path = Path(csv_path)
        if not csv_path.is_absolute():
            csv_path = manifest_dir / csv_path
        resolved.append(
            {
                "input_path": csv_path,
                "robot": robot_name,
                "input_fps": input_fps,
                "relative_path": relative_path,
            }
        )
    return resolved


def _resolve_jobs() -> list[dict]:
    if args_cli.input_file:
        return [
            {
                "input_path": Path(args_cli.input_file),
                "output_path": Path(args_cli.output_name),
                "robot": _normalize_robot_name(args_cli.robot),
                "input_fps": float(args_cli.input_fps),
                "relative_path": Path(args_cli.output_name).name,
            }
        ]

    output_dir = Path(args_cli.output_dir)
    jobs = []

    if args_cli.input_dir:
        input_dir = Path(args_cli.input_dir)
        if not input_dir.is_dir():
            raise NotADirectoryError(f"Invalid input_dir: {input_dir}")
        iterator = input_dir.rglob(args_cli.pattern) if args_cli.recursive else input_dir.glob(args_cli.pattern)
        input_paths = sorted(path for path in iterator if path.is_file())
        if not input_paths:
            raise FileNotFoundError(f"No csv files found in {input_dir} matching pattern {args_cli.pattern!r}")

        for input_path in input_paths:
            relative_output = input_path.relative_to(input_dir).with_suffix(".npz")
            output_path = output_dir / relative_output
            if output_path.exists() and not args_cli.overwrite:
                print(f"[INFO]: Skipping existing output: {output_path}")
                continue
            jobs.append(
                {
                    "input_path": input_path,
                    "output_path": output_path,
                    "robot": _normalize_robot_name(args_cli.robot),
                    "input_fps": float(args_cli.input_fps),
                    "relative_path": relative_output.as_posix(),
                }
            )
    else:
        manifest_entries = _resolve_manifest_entries(args_cli.input_manifest)
        for entry in manifest_entries:
            input_path = entry["input_path"]
            if not input_path.is_file():
                raise FileNotFoundError(f"Manifest input file not found: {input_path}")
            relative_output = (
                Path(entry["relative_path"]).with_suffix(".npz")
                if entry["relative_path"] is not None
                else Path(input_path.name).with_suffix(".npz")
            )
            output_path = output_dir / relative_output
            if output_path.exists() and not args_cli.overwrite:
                print(f"[INFO]: Skipping existing output: {output_path}")
                continue
            jobs.append(
                {
                    "input_path": input_path,
                    "output_path": output_path,
                    "robot": entry["robot"] or _normalize_robot_name(args_cli.robot),
                    "input_fps": float(entry["input_fps"]),
                    "relative_path": relative_output.as_posix(),
                }
            )

    if not jobs:
        raise FileExistsError("All batch outputs already exist. Use --overwrite to regenerate them.")
    return jobs


def main():
    jobs = _resolve_jobs()
    robot_set = {job["robot"] for job in jobs}
    if None in robot_set:
        raise ValueError("Unable to infer robot type for one or more jobs. Provide --robot or use a manifest with robot_type.")
    robot_names = sorted(robot_set)
    if len(robot_names) != 1:
        raise ValueError(f"Batch conversion currently requires the same robot type. Found: {robot_names}")

    robot_cfg, joint_names = ROBOT_MAP[robot_names[0]]

    sim_cfg = sim_utils.SimulationCfg(device=args_cli.device)
    sim_cfg.dt = 1.0 / args_cli.output_fps
    sim = SimulationContext(sim_cfg)
    scene_cfg = make_replay_scene_cfg(robot_cfg)(num_envs=1, env_spacing=2.0)
    scene = InteractiveScene(scene_cfg)
    sim.reset()
    print(f"[INFO]: Setup complete for {robot_names[0]} at output_fps={args_cli.output_fps}...")

    manifest = []
    for index, job in enumerate(jobs, start=1):
        motion_np = load_motion_csv(job["input_path"], line_range=args_cli.frame_range if args_cli.input_file else None)
        print(
            f"[INFO]: Converting {index}/{len(jobs)}: {job['input_path']} "
            f"(frames={motion_np.shape[0]}, input_fps={job['input_fps']}, output_fps={args_cli.output_fps})"
        )

        motion = torch.from_numpy(motion_np).to(torch.float32).to(sim.device)
        if motion.shape[1] != 7 + len(joint_names):
            raise ValueError(
                f"CSV column count mismatch in {job['input_path']}: got {motion.shape[1]} columns, "
                f"expected {7 + len(joint_names)} for robot {robot_names[0]}"
            )

        motion_sequence = MotionSequence(
            base_pos_input=motion[:, :3],
            base_rot_wxyz_input=motion[:, 3:7][:, [3, 0, 1, 2]],
            dof_pos_input=motion[:, 7:],
            input_fps=job["input_fps"],
            output_fps=args_cli.output_fps,
            device=sim.device,
        )

        save_motion_npz(
            simulation_app=simulation_app,
            sim=sim,
            scene=scene,
            motion=motion_sequence,
            joint_names=joint_names,
            output_name=str(job["output_path"]),
        )

        manifest.append(
            {
                "input_file": str(job["input_path"]),
                "output_file": str(job["output_path"]),
                "relative_path": job["relative_path"],
                "robot_type": robot_names[0],
                "frames": int(motion_np.shape[0]),
                "input_fps": float(job["input_fps"]),
                "output_fps": float(args_cli.output_fps),
            }
        )

    if not args_cli.input_file:
        manifest_path = Path(args_cli.manifest_path) if args_cli.manifest_path else Path(args_cli.output_dir) / "manifest.json"
        manifest_path.parent.mkdir(parents=True, exist_ok=True)
        manifest_path.write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
        print(f"[INFO]: Wrote manifest to {manifest_path}")


if __name__ == "__main__":
    main()
    # Isaac Sim teardown can hang after outputs have already been written.
    # This script is a one-shot converter, so exit the process directly on success.
    sys.stdout.flush()
    sys.stderr.flush()
    os._exit(0)
